import pytest
import torch

pytestmark = pytest.mark.integration

def test_loss_masking_integration():
    """Verifies that LossPipeline correctly applies the masks generated by SequenceTargetPipeline."""
    # TODO: re-enable when imports are restored
    # Original assertions:
    # assert "value_mask" in current_targets
    # assert "policy_mask" in current_targets
    # assert "reward_mask" in current_targets
    # assert "to_play_mask" in current_targets
    # assert current_targets["value_mask"][0].tolist() == [True, True, True]
    # assert current_targets["policy_mask"][0].tolist() == [True, False, False]
    # assert current_targets["reward_mask"][0].tolist() == [False, True, True]
    # assert current_targets["to_play_mask"][0].tolist() == [False, True, False]
    # assert "consistency_mask" in current_targets
    # assert current_targets["consistency_mask"][0].tolist() == [False, True, False]
    pytest.skip("TODO: update for old_muzero revert")

