import pytest
import torch
import torch.nn as nn
from agents.learner.losses import (
    LossPipeline,
    ValueLoss,
    PolicyLoss,
    RewardLoss,
    ToPlayLoss,
)
from agents.learner.losses.representations import (
    ScalarRepresentation,
    ClassificationRepresentation,
)
from agents.learner.target_builders import (
    SequenceTargetPipeline,
    PassThroughTargetBuilder,
)

pytestmark = pytest.mark.integration

import torch.nn.functional as F


class MockConfig:
    def __init__(self):
        self.minibatch_size = 1
        self.unroll_steps = 2

        class Game:
            num_actions = 2
            num_players = 2

        self.game = Game()
        self.value_loss_function = F.mse_loss
        self.policy_loss_function = F.cross_entropy
        self.reward_loss_function = F.mse_loss
        self.to_play_loss_factor = 1.0
        self.value_loss_factor = 1.0
        self.policy_loss_factor = 1.0
        self.reward_loss_factor = 1.0


def test_loss_masking_integration():
    """
    Verifies that LossPipeline correctly applies the masks generated by SequenceTargetPipeline.
    """
    config = MockConfig()
    device = torch.device("cpu")

    # 1. Setup Modules
    val_rep = ScalarRepresentation()
    pol_rep = ClassificationRepresentation(config.game.num_actions)
    rew_rep = ScalarRepresentation()
    tp_rep = ClassificationRepresentation(config.game.num_players)

    modules = [
        ValueLoss(
            device,
            val_rep,
            loss_fn=config.value_loss_function,
            loss_factor=config.value_loss_factor,
        ),
        PolicyLoss(
            device,
            pol_rep,
            loss_fn=config.policy_loss_function,
            loss_factor=config.policy_loss_factor,
        ),
        RewardLoss(
            device,
            rew_rep,
            loss_fn=config.reward_loss_function,
            loss_factor=config.reward_loss_factor,
        ),
        ToPlayLoss(device, tp_rep, loss_factor=config.to_play_loss_factor),
    ]

    pipeline = LossPipeline(config, modules)

    # 2. Prepare Target Builder
    builders = [
        PassThroughTargetBuilder(
            ["values", "rewards", "policies", "actions", "to_plays"]
        )
    ]
    target_builder = SequenceTargetPipeline(builders, unroll_steps=config.unroll_steps)

    # 3. Create a batch with a terminal state at index 1
    # Sequence length T = unroll_steps + 1 = 3
    # s0, s1(Terminal), s2(Post)
    B, T = 1, 3
    batch = {
        "observations": torch.zeros((B, T, 1)),
        "unroll_observations": torch.zeros((B, T, 1)),
        "actions": torch.zeros((B, T), dtype=torch.long),
        "rewards": torch.zeros((B, T - 1)),
        "values": torch.zeros((B, T - 1)),
        "policies": torch.ones((B, T - 1, config.game.num_actions))
        / config.game.num_actions,
        "to_plays": torch.zeros((B, T - 1), dtype=torch.long),
        "dones": torch.tensor([[False, True, True]]),
        "is_same_game": torch.tensor([[True, True, True]]),
    }

    # Padded data in current_targets will have length T=3
    current_targets = {}
    target_builder.build_targets(batch, {}, nn.Module(), current_targets)

    # 4. Correct Root Policy Padding (SequencePadder pads with zeros by default)
    # Root policy is index 0. Policy mask at index 0 is True, so it must sum to 1.
    current_targets["policies"][:, 0] = 1.0 / config.game.num_actions

    # 5. Mock Predictions
    predictions = {
        "state_value": torch.zeros((B, T, 1)),
        "policy_logits": torch.zeros((B, T, config.game.num_actions)),
        "reward_logits": torch.zeros((B, T, 1)),
        "to_play_logits": torch.zeros((B, T, config.game.num_players)),
    }

    # Essential keys for run()
    current_targets["weights"] = torch.ones(B)
    current_targets["gradient_scales"] = torch.ones((1, T))

    # 5. Run pipeline
    total_loss_dict, loss_dict, priorities = pipeline.run(predictions, current_targets)

    # 6. Verify Masks via Metrics (unweighted losses use the mask count)
    # If policy is masked at index 1 (terminal), its valid count should be 1 (root s0).
    # Mask: [T, F, F]
    # Expected valid count for policy: 1

    # Actually I'll verify the masks directly in current_targets
    assert "value_mask" in current_targets
    assert "policy_mask" in current_targets
    assert "reward_mask" in current_targets
    assert "to_play_mask" in current_targets

    # Terminal at index 1
    # value: [T, T, T]
    assert current_targets["value_mask"][0].tolist() == [True, True, True]
    # policy: s0 True, s1(Terminal) False, s2(Post) False
    assert current_targets["policy_mask"][0].tolist() == [True, False, False]
    # reward: s0 False, s1(Terminal) True, s2(Post) True
    assert current_targets["reward_mask"][0].tolist() == [False, True, True]
    # to_play: s0 False, s1(Terminal) True, s2(Post) False
    assert current_targets["to_play_mask"][0].tolist() == [False, True, False]

    # Verify auxiliary masks
    assert "consistency_mask" in current_targets
    assert current_targets["consistency_mask"][0].tolist() == [False, True, False]

    print("Integration Loss Masking Verified!")
