import pytest
import torch
import torch.nn as nn
import search.search_py.modular_search as sm
import search.search_py.nodes as sn
from torch.distributions import Categorical
from types import SimpleNamespace

pytestmark = pytest.mark.unit

def test_mcts_no_interior_masking():
    """
    Tier 1 Unit Test: No Interior Action Masking
    - Legal action masking is applied at the root node (s^0).
    - Explicitly assert that masking is not applied to subsequent hypothetical nodes (s^k) 
      generated by the dynamics function.
    """
    num_actions = 4
    config = SimpleNamespace(
        num_simulations=10,
        num_actions=num_actions,
        search_batch_size=0, # sequential simulation
        gumbel=False,
        gumbel_m=4, 
        support_range=None,
        use_virtual_mean=False,
        virtual_loss=0.0,
        known_bounds=None,
        min_max_epsilon=0.01,
        bootstrap_method="value_function",
        discount_factor=0.99,
        num_players=1,
        dirichlet_alpha=0.3,
        dirichlet_epsilon=0.25,
        use_dirichlet=False,
        policy_extraction="mcts",
        puct_c1=1.25,
        puct_c2=19652,
        pb_c_init=1.25,
        pb_c_base=19652,
        gumbel_cvisit=50,
        gumbel_cscale=1.0,
        stochastic=False,
        selection_method="puct",
        pruning_method="none",
        pruning_method_internal="none",
        use_value_prefix=False,
        max_depth=50,
        max_search_depth=50,
        backprop_method="average",
        game=SimpleNamespace(num_players=1),
    )
    
    # We MUST patch correctly BEFORE instantiating OR ensure patches hit the correct references.
    interior_nodes_allowed_actions = []
    root_node_allowed_actions = []
    
    original_expand = sn.DecisionNode.expand
    
    def hooked_expand(node, allowed_actions, *args, **kwargs):
        if node.parent is None:
            root_node_allowed_actions.append(allowed_actions)
        else:
            interior_nodes_allowed_actions.append(allowed_actions)
        return original_expand(node, allowed_actions, *args, **kwargs)

    # Patch both references to be absolutely sure.
    sn.DecisionNode.expand = hooked_expand
    sm.DecisionNode.expand = hooked_expand
    
    try:
        search_engine = sm.ModularSearch(config, num_actions=num_actions, device=torch.device("cpu"))
        
        class MockNetwork(nn.Module):
            def obs_inference(self, obs):
                from modules.models.inference_output import InferenceOutput
                return InferenceOutput(
                    recurrent_state={"dynamics": torch.zeros(1)},
                    value=torch.tensor([0.0]),
                    policy=Categorical(logits=torch.zeros(1, num_actions)),
                    reward=None,
                    to_play=torch.tensor([0]),
                    extras={}
                )
                
            def hidden_state_inference(self, state, action):
                from modules.models.inference_output import InferenceOutput
                # Returning positive value to ensure simulation doesn't visit same state forever?
                # Actually PUCT will visit others anyway.
                return InferenceOutput(
                    recurrent_state={"dynamics": torch.zeros(1)},
                    value=torch.tensor([0.1]),
                    policy=Categorical(logits=torch.zeros(1, num_actions)),
                    reward=torch.tensor([0.0]),
                    to_play=torch.tensor([0]),
                    extras={}
                )

        network = MockNetwork()
        
        info = {
            "player": 0, 
            "legal_moves": [0]
        }
        
        # Run MCTS
        _, _, target_policy, best_action, _ = search_engine.run(
            observation=torch.zeros(1),
            info=info,
            agent_network=network,
            exploration=False
        )
        
        # Debugging
        print(f"DEBUG: TARGET POLICY={target_policy.tolist()}, BEST={best_action}")
        print(f"DEBUG: ROOT_ALLOWED={root_node_allowed_actions}")
        print(f"DEBUG: INTERIOR_COUNT={len(interior_nodes_allowed_actions)}")

        # Root must pick action 0
        assert target_policy[0].item() > 0.99, f"Root selection failed: {target_policy}"
        assert best_action == 0
        # Explicit check for masked actions being effectively zero
        for i in range(1, num_actions):
            assert target_policy[i].item() < 1e-5, f"Illegal action {i} was not masked: {target_policy[i]}"
        
        # Verify root masking call
        assert len(root_node_allowed_actions) >= 1
        assert list(root_node_allowed_actions[0]) == [0]
        
        # Verify internal NO masking
        assert len(interior_nodes_allowed_actions) > 0, "Tree didn't explore"
        for acts in interior_nodes_allowed_actions:
            # Interior node MUST NOT be masked to [0]
            assert len(acts) == num_actions, f"Interior node masked: {acts}"
            assert list(sorted(list(acts))) == [0, 1, 2, 3]

        print("Passed MCTS Interior Masking Mathematical Strictness Test!")

    finally:
        # Restore original
        sn.DecisionNode.expand = original_expand
        sm.DecisionNode.expand = original_expand
